DISPLAY_WIDTH, DISPLAY_HEIGHT = 1400, 900       #display dimensions                                             1400,900 
TILE_SIZE = DISPLAY_WIDTH/20                    #how large 1 tile is                                            20
PLAYER_SPEED = DISPLAY_WIDTH/200                #how fast player moves                                          200
MOVEMENT_BORDER = 0.5                           #where player can move to                                       0.5 
GRAVITY = DISPLAY_HEIGHT/1125                   #how fast player falls                                          1125
PLAYER_JUMP_SPEED = DISPLAY_HEIGHT/-45          #how high player jumps                                          -45
PLAYER_SIZE = TILE_SIZE*0.75,TILE_SIZE*1.5      #how big player is                                              0.75,1.5
ANIMATION_SPEED = 0.03                          #how fast animation is                                          0.03 
PROJECTILE_ANIMATION_SPEED = 0.2                #how fast animation is                                          0.2
MELEE_ANIMATION_SPEED = 0.3                     #how fast animation is                                          0.3
PROJECTILE_ENEMY_ANIMATION_SPEED = 0.5          #how fast animation is                                          0.5
BASELINE = 2                                    #how many tiles above bottom of screen is base                  2
BASEMAX = 2                                     #how many tiles is the max for the base to be raised            2
L1_WIDTH = 5                                    #how wide L1 can be                                             5
L2_WIDTH = 4                                    #how wide L2 can be                                             4
L3_WIDTH = 2                                    #how wide L3 can be                                             2
L1_SEPARATION = 2                               #how many tiles separation 2                                    2
L2_SEPARATION = 2                               #how many tiles separation 2                                    2
L3_SEPARATION = 2                               #how many tiles separation 2                                    2
PLAYER_HEALTH = 5                               #max health                                                     5
VEL_RANGE = 8                                   #max possible velocity                                          8
KD_RANGE = 20                                   #max allowed value for KD                                       20
PROJECTILE_SPEED = DISPLAY_WIDTH/140            #how fast projectiles move                                      10
PROJECTILE_SIZE = TILE_SIZE*0.7, TILE_SIZE*0.5  #how large projectiles are                                      0.7,0.5
ALPHABET = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"]